### ISSUE TITLE
reasnow是否可以协助我进行部署，我愿意付费，请联系我QQ1579829883

### ISSUE THREAD

**Issue by AEROVN** [wdragondragon/ApexRecoils#1]
我在闲鱼上看到了类似您的项目，github上偶然发现您的开源，奈何python经验不足无法自行部署。如果您有时间希望可以添加我的QQ，我愿意付费一个您满意的价格，协助我在我的服务器上进行部署。我的设备是Reasnow S1+C1 并且承诺仅个人使用。

**Comment by AEROVN** [comment]
因为我没有两台设备，所以hdmi采集实现困难；我想通过obs推流至云服务器进行运算，再通过键鼠盒子反馈到键盘上

**Comment by luckylemonade24** [comment]
云游戏其实不错，
